export const START_LOADING = 'START_LOADING'
export const FINISH_LOADING = 'FINISH_LOADING'
export const MENU = 'MENU'

export const FETCH_INIT = 'FETCH_INIT'

export const FETCH_ME_PROFILE = 'FETCH_ME_PROFILE'
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS'
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST'
export const FETCH_MY_SAVED_TRACKS = 'FETCH_MY_SAVED_TRACKS'

export const PLAY_SONG = 'PLAY_SONG'

export const PROVIDE_TOKEN = 'PROVIDE_TOKEN'

export const HOME_VIEWS = 'HOME_VIEWS'
export const PLAYLIST_VIEWS = 'PLAYLIST_VIEWS'
